### ISSUE TITLE
Stop breaking symlinks

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-image-rsyncd#5]
add `munge symlinks = no` to the server config

**Comment by Duske** [comment]
I can take care of this simple issue if you want

**Comment by EugenMayer** [comment]
sure, any contribution is valuable!

**Comment by Duske** [comment]
The PR (#6) is ready, but I could only check if it builds succesfully (working on a windows machine).
I hope that's okay for such a small change like this

**Comment by EugenMayer** [comment]
well you can build the image locally, then fire up the example project in docker-sync or the docker-sync-boilerplate for rsync and see, if things still work. Thats kinda the effort here, the actual change is minimal, as you already noticed. Thanks for the work!
